**SENTIMENT ANALYSIS FOR HATE SPEECH DETECTION**

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk 
nltk.download('punkt')
import numpy as np
import re

[nltk_data] Downloading package punkt to C:\Users\Ayush's
[nltk_data]     Workhorse\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [3]:
nltk.download('stopwords')
nltk.download('plunkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Ayush's
[nltk_data]     Workhorse\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Error loading plunkt: Package 'plunkt' not found in index
[nltk_data] Downloading package wordnet to C:\Users\Ayush's
[nltk_data]     Workhorse\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [4]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")
train_data.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

# New Section

# New Section

In [5]:
def delete_similar(inp, pat):
    r = re.findall(pat, inp)
    for i in r:
        inp = re.sub(i, '', inp)
    return inp

In [6]:
train_data['Data_without_user']=np.vectorize(delete_similar)(train_data['tweet'],"@[\w]*")
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  
0    when a father is dysfunctional and is so sel...  
1    thanks for #lyft credit i can't use cause th...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation

In [7]:
train_data['Data_without_user'] = train_data['Data_without_user'].apply(lambda x: x.lower())
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  
0    when a father is dysfunctional and is so sel...  
1    thanks for #lyft credit i can't use cause th...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation

In [8]:
train_data['Data_without_user'] = train_data['Data_without_user'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i can t use cause th...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation

In [9]:
train_data['Data_without_user'] = train_data['Data_without_user'].apply(lambda x: re.sub(r'[^a-zA-Z]',' ',x))
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i can t use cause th...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation

In [10]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [11]:
train_data['tokenized_data'] = train_data['Data_without_user'].apply(lambda x: word_tokenize(x))
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i can t use cause th...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   

                                      tokenized_data  
0  [when, a, father, is, dysfunctional, and, is, ...  
1  [thanks, for, lyft, credit, i, can, t, use, ca...  
2                            [bihday, your, majesty]  
3  [model, i, love, u, take, with, u, all, the, t...  
4             [factsguide, society, now, motivation]

In [12]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [13]:
train_data['Data_without_stopwords'] = train_data['tokenized_data'].apply(lambda x: [i for i in x if not i in stop_words])
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i can t use cause th...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   

                                      tokenized_data  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, t, use, ca...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   

                              Data_without_stopwords  
0  [father, dysfunctional, selfish, drags, kids, ...  
1  [thanks, lyft, credit, use, cause, offer, whee...  
2                                  [bihday, majesty]  
3                [model, love, u, take, u, time, ur]  
4                  [factsguide, society, motivation]

In [14]:
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [15]:
train_data['stemmed_data'] = train_data['Data_without_stopwords'].apply(lambda x:' '.join([stemming.stem(i) for i in x]))
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i can t use cause th...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   

                                      tokenized_data  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, t, use, ca...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   

                              Data_without_stopwords  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   

                                        stemmed_data  
0      father dysfunct selfish drag kid dysfunct run  
1  thank lyft credit use caus offer wheelchair va...  
2                                     bihday majesti  
3                        model love u take u time ur  
4                            factsguid societi motiv

In [16]:
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizing = WordNetLemmatizer()

In [17]:
train_data['lemmatized_data'] = train_data['Data_without_stopwords'].apply(lambda x:' '.join([lemmatizing.lemmatize(i) for i in x]))
train_data.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                   Data_without_user  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i can t use cause th...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   

                                      tokenized_data  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, t, use, ca...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   

                              Data_without_stopwords  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   

                                        stemmed_data  \
0      father dysfunct selfish drag kid dysfunct run   
1  thank lyft credit use caus offer wheelchair va...   
2                                     bihday majesti   
3                        model love u take u time ur   
4                            factsguid societi motiv   

                                     lemmatized_data  
0  father dysfunctional selfish drag kid dysfunct...  
1  thanks lyft credit use cause offer wheelchair ...  
2                                     bihday majesty  
3                        model love u take u time ur  
4                      factsguide society motivation

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
vectoriser = CountVectorizer(max_df=0.90, min_df=2,max_features=1000,stop_words='english')
vectoriser

CountVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [19]:
trainstem = vectoriser.fit_transform(train_data['stemmed_data'])
trainstem

<31962x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 134042 stored elements in Compressed Sparse Row format>

In [20]:
trainlem = vectoriser.fit_transform(train_data['lemmatized_data'])
trainlem

<31962x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 123672 stored elements in Compressed Sparse Row format>

In [21]:
trainstem.toarray()
trainlem.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectoriser = TfidfVectorizer(max_df=0.90,min_df=2,max_features=1000,stop_words='english')
tfidf_vectoriser

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [23]:
traintfidfstem = tfidf_vectoriser.fit_transform(train_data['stemmed_data'])
traintfidfstem.toarray()
traintfidflem = tfidf_vectoriser.fit_transform(train_data['lemmatized_data'])
traintfidflem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
test_data

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [25]:
test_data['Data_without_user'] = np.vectorize(delete_similar)(test_data['tweet'], "@[\w]*")
test_data.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                   Data_without_user  
0  #studiolife #aislife #requires #passion #dedic...  
1    #white #supremacists want everyone to see th...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...  
5                        choose to be   :) #momtips   
6  something inside me dies 💦💿✨  eyes nes...  
7  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...  
8      i will never understand why my dad left me...  
9  #delicious   #food #lovelife #capetown mannaep...

In [26]:
test_data['Data_without_user'] = test_data['Data_without_user'].apply(lambda x: x.lower())
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  
0  #studiolife #aislife #requires #passion #dedic...  
1    #white #supremacists want everyone to see th...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...

In [27]:
test_data['Data_without_user'] = test_data['Data_without_user'].apply(lambda x: re.sub(r'[^\w\s]',' ', x))
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd  bihday to my amazing  hilarious  nephew...

In [28]:
test_data['Data_without_user'] = test_data['Data_without_user'].apply(lambda x: re.sub(r'[^a-zA-Z0-9]',' ', x))
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd  bihday to my amazing  hilarious  nephew...

In [29]:
test_data['Data_without_user'] = test_data['Data_without_user'].apply(lambda x: re.sub(r'[^a-zA-Z]',' ',x))
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4     rd  bihday to my amazing  hilarious  nephew...

In [30]:
test_data['tweet_token'] = test_data['Data_without_user'].apply(lambda x: word_tokenize(x))
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   

                                         tweet_token  
0  [studiolife, aislife, requires, passion, dedic...  
1  [white, supremacists, want, everyone, to, see,...  
2  [safe, ways, to, heal, your, acne, altwaystohe...  
3  [is, the, hp, and, the, cursed, child, book, u...  
4  [rd, bihday, to, my, amazing, hilarious, nephe...

In [31]:
test_data['Data_without_stopwords'] = test_data['tweet_token'].apply(lambda x: [i for i in x if not i in stop_words])
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   

                                         tweet_token  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, to, see,...   
2  [safe, ways, to, heal, your, acne, altwaystohe...   
3  [is, the, hp, and, the, cursed, child, book, u...   
4  [rd, bihday, to, my, amazing, hilarious, nephe...   

                              Data_without_stopwords  
0  [studiolife, aislife, requires, passion, dedic...  
1  [white, supremacists, want, everyone, see, new...  
2  [safe, ways, heal, acne, altwaystoheal, health...  
3  [hp, cursed, child, book, reservations, alread...  
4  [rd, bihday, amazing, hilarious, nephew, eli, ...

In [32]:
test_data['tweet_stemmed'] = test_data['Data_without_stopwords'].apply(lambda x: ' '.join([stemming.stem(i) for i in x]))
test_data['tweet_stemmed'].head()

0    studiolif aislif requir passion dedic willpow ...
1     white supremacist want everyon see new bird movi
2            safe way heal acn altwaystoh healthi heal
3    hp curs child book reserv alreadi ye harrypott...
4    rd bihday amaz hilari nephew eli ahmir uncl da...
Name: tweet_stemmed, dtype: object

In [33]:
test_data['lemmatized_data'] = test_data['Data_without_stopwords'].apply(lambda x: ' '.join([lemmatizing.lemmatize(i) for i in x]))
test_data.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                   Data_without_user  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   

                                         tweet_token  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, to, see,...   
2  [safe, ways, to, heal, your, acne, altwaystohe...   
3  [is, the, hp, and, the, cursed, child, book, u...   
4  [rd, bihday, to, my, amazing, hilarious, nephe...   

                              Data_without_stopwords  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, see, new...   
2  [safe, ways, heal, acne, altwaystoheal, health...   
3  [hp, cursed, child, book, reservations, alread...   
4  [rd, bihday, amazing, hilarious, nephew, eli, ...   

                                       tweet_stemmed  \
0  studiolif aislif requir passion dedic willpow ...   
1   white supremacist want everyon see new bird movi   
2          safe way heal acn altwaystoh healthi heal   
3  hp curs child book reserv alreadi ye harrypott...   
4  rd bihday amaz hilari nephew eli ahmir uncl da...   

                                     lemmatized_data  
0  studiolife aislife requires passion dedication...  
1  white supremacist want everyone see new bird m...  
2   safe way heal acne altwaystoheal healthy healing  
3  hp cursed child book reservation already yes h...  
4  rd bihday amazing hilarious nephew eli ahmir u...

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
vec_bow = CountVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
vec_bow

CountVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [35]:
test_bs = vec_bow.fit_transform(test_data['tweet_stemmed'])
test_bs.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
test_bl = vec_bow.fit_transform(test_data['lemmatized_data'])
test_bl.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvec = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
tfidfvec

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [38]:
testtfidf_stem = tfidfvec.fit_transform(test_data['tweet_stemmed'])
testtfidf_stem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
testtfidf_lemm = tfidfvec.fit_transform(test_data['lemmatized_data'])
testtfidf_lemm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [90]:
X=traintfidflem
y=train_data['label']    
k=X.toarray()
k[-1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [42]:
xtrain, xtest, ytrain, ytest=train_test_split(X,y,test_size=0.35, random_state=42)

In [43]:
lr=LogisticRegression()
lr.fit(xtrain, ytrain)

LogisticRegression()

In [44]:
prediction_lr=lr.predict(xtest)

In [45]:
print(accuracy_score(prediction_lr, ytest))
print(confusion_matrix(prediction_lr, ytest))
print(classification_report(prediction_lr, ytest))

0.9474389916867793
[[10343   533]
 [   55   256]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     10876
           1       0.32      0.82      0.47       311

    accuracy                           0.95     11187
   macro avg       0.66      0.89      0.72     11187
weighted avg       0.98      0.95      0.96     11187



In [46]:
svc=SVC()
svc.fit(xtrain,ytrain)
predict_svc=svc.predict(xtest)

In [47]:
print(accuracy_score(predict_svc, ytest))
print(confusion_matrix(predict_svc, ytest))
print(classification_report(predict_svc, ytest))

0.9495843389648699
[[10339   505]
 [   59   284]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     10844
           1       0.36      0.83      0.50       343

    accuracy                           0.95     11187
   macro avg       0.68      0.89      0.74     11187
weighted avg       0.97      0.95      0.96     11187



In [48]:
nb=GaussianNB()
nb.fit(xtrain.toarray(), ytrain)
predict_nb=nb.predict(xtest.toarray())

In [49]:
print(accuracy_score(predict_nb, ytest))
print(confusion_matrix(predict_nb, ytest))
print(classification_report(predict_nb, ytest))

0.5820148386520068
[[5796   74]
 [4602  715]]
              precision    recall  f1-score   support

           0       0.56      0.99      0.71      5870
           1       0.91      0.13      0.23      5317

    accuracy                           0.58     11187
   macro avg       0.73      0.56      0.47     11187
weighted avg       0.72      0.58      0.49     11187



In [50]:
X1=traintfidfstem
y1=train_data['label']

In [51]:
x1train, x1test, y1train, y1test=train_test_split(X1, y1, test_size=0.35, random_state=42)

In [52]:
lr1=LogisticRegression()
lr1.fit(x1train, ytrain)

LogisticRegression()

In [53]:
predict_lr1=lr1.predict(x1test)

In [54]:
print(accuracy_score(predict_lr1, y1test))
print(confusion_matrix(predict_lr1, y1test))
print(classification_report(predict_lr1, y1test))

0.9480647179762224
[[10338   521]
 [   60   268]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     10859
           1       0.34      0.82      0.48       328

    accuracy                           0.95     11187
   macro avg       0.67      0.88      0.73     11187
weighted avg       0.98      0.95      0.96     11187



In [64]:
svc1=SVC()
svc1.fit(x1train,y1train)
predict_svc1=svc1.predict(x1test)
predict_svc1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [63]:
print(accuracy_score(predict_svc1, y1test))
print(confusion_matrix(predict_svc1, y1test))
print(classification_report(predict_svc1, y1test))

0.9506570126039152
[[10339   493]
 [   59   296]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     10832
           1       0.38      0.83      0.52       355

    accuracy                           0.95     11187
   macro avg       0.68      0.89      0.75     11187
weighted avg       0.97      0.95      0.96     11187



In [57]:
nb1=GaussianNB()
nb1.fit(x1train.toarray(), y1train)
predict_nb1=nb1.predict(x1test.toarray())

In [58]:
print(accuracy_score(predict_nb1, y1test))
print(confusion_matrix(predict_nb1, y1test))
print(classification_report(predict_nb1, y1test))

0.5605613658711004
[[5565   83]
 [4833  706]]
              precision    recall  f1-score   support

           0       0.54      0.99      0.69      5648
           1       0.89      0.13      0.22      5539

    accuracy                           0.56     11187
   macro avg       0.72      0.56      0.46     11187
weighted avg       0.71      0.56      0.46     11187



test DATA

In [102]:
test_lr=lr.predict(testtfidf_lemm)
test_lr

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [101]:
test_svc=svc.predict(testtfidf_lemm)
test_svc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
test_nb=nb.predict(testtfidf_lemm.toarray())
test_nb

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [72]:
print(x1test.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
